name: Deploy do Nexus na Vercel

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    name: Testes
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Configurar Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Instalar dependências
      run: npm ci
    
    - name: Executar linting
      run: npm run lint
    
    - name: Executar testes
      run: npm test
  
  deploy:
    name: Deploy na Vercel
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'pull_request'
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Instalar Vercel CLI
        run: npm install -g vercel
      
      - name: Pull Configurações da Vercel
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      
      - name: Build do Projeto
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
      
      - name: Deploy para Preview
        if: github.event_name == 'pull_request'
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
      
      - name: Deploy para Produção
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
      
      - name: Deploy para Ambiente de Desenvolvimento
        if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
        run: |
          vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }} > deployment-url.txt
          echo "Deployed to $(cat deployment-url.txt)"
